title = "Dartic Solution"
languageCode = "en-us"
baseURL = "http://localhost:1313/"
theme = "massively"

publishDir = "docs"


[languages]
[languages.en]
  languageName = "English"
[languages.fr]
  languageName = "Français"
  title = "Dartic Solution"
