title = "Dartic Solutions"
languageCode = "en-us"
baseURL = "https://faryaio.github.io/dartic-solutions-website/"
theme = "massively"

publishDir = "docs"


[languages]
[languages.en]
  languageName = "English"
[languages.fr]
  languageName = "Français"
  title = "Dartic Solutions"
